# BoardConfig for for both marlin and sailfish

TW_THEME := portrait_hdpi
TW_INCLUDE_FB2PNG := true
LZMA_RAMDISK_TARGETS := recovery,boot
BOARD_KERNEL_IMAGE_NAME := Image.lz4-dtb
TARGET_RECOVERY_FSTAB := device/google/marlin/twrp.fstab
BOARD_SUPPRESS_SECURE_ERASE := true
TARGET_RECOVERY_QCOM_RTC_FIX := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_DEFAULT_BRIGHTNESS := "80"
TW_INCLUDE_REPACKTOOLS := true
TW_EXCLUDE_UBSAN := true
AB_OTA_UPDATER := true
TWRP_INCLUDE_LOGCAT := true
BOARD_VNDK_RUNTIME_DISABLE := true
TARGET_USES_LOGD := true
TW_USE_TOOLBOX := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_EXCLUDE_TZDATA := true
TW_EXCLUDE_NANO := true
